### ISSUE TITLE
Migrate to the new project site format.

### ISSUE THREAD

**Issue by souravbadami** [OWASP/www-project-bug-logging-tool#1]

**Comment by souravbadami** [comment]
I'm picking it up.
cc @fredfalcon.

**Comment by fredfalcon** [comment]
@souravbadami how is this going?

**Comment by souravbadami** [comment]
@fredfalcon - Basic bare bones are up and running. We need to finalize on what can we add on the left pane.
Here: https://owasp.org/www-project-bug-logging-tool.
